apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-demo
  namespace: pv-demo
spec:
  storageClassName: ""
  capacity:
    storage: 100G
  accessModes:
    - ReadWriteOnce
  claimRef:
    namespace: pv-demo
    name: pv-claim-demo
  gcePersistentDisk:
    pdName: tf-sample-gke-disk
    fsType: ext4
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: topology.kubernetes.io/zone
              operator: In
              values:
                - europe-west1-b
                - europe-west1-c
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pv-claim-demo
  namespace: pv-demo
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100G
